<?php

########################################################################
# Extension Manager/Repository config file for ext: "cundd_composer"
#
# Auto generated by Extension Builder 2012-12-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cundd Composer',
	'description' => 'Composer support for TYPO3 CMS',
	'category' => 'module',
	'author' => 'Daniel Corn',
	'author_email' => 'info@cundd.net',
	'author_company' => 'cundd',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>